CREATE DATABASE QLNT
GO
USE QLNT
GO
CREATE TABLE USER_USE(
	FULLNAME NVARCHAR(45) NOT NULL,
	USERNAME VARCHAR(30) PRIMARY KEY,
	PASSWORD VARCHAR(50) NOT NULL,
	SEX NVARCHAR(10) NOT NULL,
	PERMISION INT NOT NULL DEFAULT 1
)
GO

CREATE TABLE MEDICINE(
	ID_MEDICINE INT NOT NULL IDENTITY PRIMARY KEY,
	MEDICINE_NAME NVARCHAR(50) NOT NULL,
	TYPE_MEDICINE NVARCHAR(30) NOT NULL,
	NUMBER_MEDICINE INT NOT NULL,
	DAY_OF_MANUFUTURE_MEDICINE DATE NOT NULL,
	EXPIRATION_DAY_MEDICINE DATE NOT NULL,
	PRICE_MEDICINE FLOAT NOT NULL,
	MORE_MEDICINE NVARCHAR(100)
)
GO
CREATE PROC LOGIN
@USERNAME VARCHAR(30), @PASSWORD VARCHAR(50)
AS
BEGIN
	SELECT USERNAME, PASSWORD FROM USER_USE WHERE USERNAME = @USERNAME AND PASSWORD = @PASSWORD
END
GO
INSERT INTO USER_USE (FULLNAME,USERNAME,PASSWORD,SEX,PERMISION) VALUES  (N'NGUYỄN THÊ ANH','admin','12345678',N'Nam',1)
GO
INSERT INTO USER_USE (FULLNAME,USERNAME,PASSWORD,SEX,PERMISION) VALUES  (N'NGUYỄN THANH','staff','012345678',N'Nữ',0)
GO

CREATE INDEX NAME_MEDICINE ON MEDICINE (MEDICINE_NAME)
GO
CREATE PROC CREATE_MEDICINE
@MEDICINE_NAME NVARCHAR(50),@TYPE_MEDICINE NVARCHAR(30),@NUMBER_MEDICINE INT,
@DAY_OF_MANUFUTURE_MEDICINE DATE,
@EXPIRATION_DAY_MEDICINE DATE ,
@PRICE_MEDICINE FLOAT,
@MORE_MEDICINE NVARCHAR(100)
AS
BEGIN


	INSERT INTO MEDICINE (MEDICINE_NAME, TYPE_MEDICINE,
	NUMBER_MEDICINE, DAY_OF_MANUFUTURE_MEDICINE, 
	EXPIRATION_DAY_MEDICINE, PRICE_MEDICINE,MORE_MEDICINE) VALUES(@MEDICINE_NAME, @TYPE_MEDICINE, @NUMBER_MEDICINE, 
	@DAY_OF_MANUFUTURE_MEDICINE, @EXPIRATION_DAY_MEDICINE,@PRICE_MEDICINE,@MORE_MEDICINE)
END
GO
CREATE PROC UPDATE_MEDICINE
@ID INT,@MEDICINE_NAME NVARCHAR(50),@TYPE_MEDICINE NVARCHAR(30),@NUMBER_MEDICINE INT,
@DAY_OF_MANUFUTURE_MEDICINE DATE,
@EXPIRATION_DAY_MEDICINE DATE ,
@PRICE_MEDICINE FLOAT,
@MORE_MEDICINE NVARCHAR(100)
AS
BEGIN
	DECLARE @isexist INT;
	SELECT @isexist = MEDICINE.NUMBER_MEDICINE from MEDICINE
	IF (@isexist > 0)
	BEGIN
	UPDATE MEDICINE
	SET  MEDICINE_NAME = @MEDICINE_NAME, TYPE_MEDICINE = @TYPE_MEDICINE, NUMBER_MEDICINE= @NUMBER_MEDICINE, 
	DAY_OF_MANUFUTURE_MEDICINE = @DAY_OF_MANUFUTURE_MEDICINE, 
	EXPIRATION_DAY_MEDICINE = @EXPIRATION_DAY_MEDICINE,PRICE_MEDICINE = @PRICE_MEDICINE, MORE_MEDICINE = @MORE_MEDICINE
	WHERE ID_MEDICINE = @ID
	END
	ELSE
	DELETE MEDICINE WHERE ID_MEDICINE = @ID

END
GO
CREATE PROC DELETE_MEDICINE
@ID INT
AS
BEGIN
DELETE FROM MEDICINE WHERE ID_MEDICINE = @ID
END
GO
CREATE PROC BUY_MEDICINE
@ID INT, @NUMBER_MEDICINE INT
AS
BEGIN
DECLARE @isexist INT;
	SELECT @isexist = MEDICINE.NUMBER_MEDICINE from MEDICINE WHERE ID_MEDICINE = @ID
	IF (@isexist > 0)
		UPDATE MEDICINE SET NUMBER_MEDICINE = @NUMBER_MEDICINE WHERE ID_MEDICINE = @ID
	ELSE
		DELETE MEDICINE WHERE ID_MEDICINE = @ID
END
GO
CREATE PROC INSERT_USER
@FULLNAME NVARCHAR(30), @USERNAME VARCHAR(30), @PASSWORD VARCHAR(50), @SEX NVARCHAR(10), @PERMISION INT
AS
BEGIN
INSERT INTO USER_USE (FULLNAME, USERNAME, PASSWORD, SEX, PERMISION) VALUES (@FULLNAME, @USERNAME, @PASSWORD, @SEX, @PERMISION) 
END
GO 
CREATE PROC UPDATE_USER
@FULLNAME NVARCHAR(30), @USERNAME VARCHAR(30), @SEX NVARCHAR(10), @PERMISION INT
AS
BEGIN
UPDATE USER_USE SET FULLNAME = @FULLNAME, USERNAME = @USERNAME, SEX = @SEX, PERMISION=@PERMISION where USERNAME = @USERNAME
END
GO
CREATE PROC DEL_USER
@USERNAME VARCHAR(30)
AS
BEGIN
DELETE FROM USER_USE WHERE USERNAME = @USERNAME
END
GO
EXEC CREATE_MEDICINE @MEDICINE_NAME = N'Thuốc giảm đau',@TYPE_MEDICINE = N'Sốt thường', @NUMBER_MEDICINE = 3, 
	@DAY_OF_MANUFUTURE_MEDICINE = '12-03-2021', 
	@EXPIRATION_DAY_MEDICINE = '09-21-2022',@PRICE_MEDICINE = 12000, @MORE_MEDICINE = N'Thuốc giảm đau 1-12 tháng tuổi'
GO
EXEC CREATE_MEDICINE @MEDICINE_NAME = N'Thuốc đau họng',@TYPE_MEDICINE = N'Tai mũi họng', @NUMBER_MEDICINE = 13, 
	@DAY_OF_MANUFUTURE_MEDICINE = '11-06-2022', 
	@EXPIRATION_DAY_MEDICINE = '12-06-2022',@PRICE_MEDICINE = 52000,@MORE_MEDICINE = N'Thuốc đau họng cho trẻ và người trưởng thành, chống chỉ định với người lớn tuổi'
GO
